export const CarouselProducts =[
  {
    id: 1,
    image: "/images/Custom-Wholesale-Silk-Duvet-1.webp",
    alt: "Custom Wholesale Silk Duvet",
    title: "Printed Silk Bedding",
    description: "Sinosilk's printed silk bedding infuses your ehn hand at every point of your designing, solving any challenges you meet.",
    href: "/summer-duvet",
  },
  {
    id: 2,
    image: "/images/long-strand-mulberry-silk-duvet-1.webp",
    alt: "Long Strand Mulberry Silk Duvet",
    title: "Long Strand Mulberry Silk Duvet",
    description: "Feeling monotonous about solid colors? Our two-tone ing yougive you advice based on your preferences and aesthetic perspective.",
    href: "/long-strand-mulberry-silk-duvet",
  },
  {
    id: 3,
    image: "/images/luxury-silk-satin-bedding-pure-mulberry-silk-duvet-1.webp",
    alt: "Luxury Silk Satin Bedding",
    title: "Luxury Silk Satin Bedding",
    description: "Sinosilk's silk jacquard bedding boasts lustroung sets captiva the these beddings still furnish your sleep with incredible comfort.",
    href: "/luxury-silk-satin-bedding-pure-mulberry-silk-duvet",
  },
  {
    id: 4,
    image: "/images/natural-soft-silk-quilt-1.webp",
    alt: "Natural Soft Silk Quilt",
    title: "Natural Soft Silk Quilt",
    description: "Our classic silk duvet is crafted from 100% msons. The timele while the natural silk filling ensures a restful night's sleep.",
    href: "/natural-soft-silk-quilt",
  },
  {
    id: 5,
    image: "/images/summer-mulberry-silk-print-duvet-1.webp",
    alt: "Summer Mulberry Silk Print Duvet",
    title: "Summer Mulberry Silk Print Duvet",
    description: "Upgrade your bedroom with our luxury silk beddin Eaant look, perfect for those who value both comfort and style.",
    href: "/summer-mulberry-silk-print-duvet",
  },
];

export const products = [
      {
        id: 1,
        image: '/images/allseason.webp',
        alt: '19mm Silk Duvet',
        title: '19mm Silk Duvet',
        description: 'Luxury mulberry silk duvet for all seasons',
        href: '19mm-silk-duvet',
        categories: ['all-season', 'hotel'],
      },
      {
        id: 2,
        image: '/images/products/pillowcase-1.jpg',
        alt: 'Silk Pillowcase Set',
        title: 'Silk Pillowcase Set',
        description: 'Set of 2 pure silk pillowcases',
        href: 'silk-pillowcase-set',
        categories: ['all-season'],
      },
      {
        id: 3,
        image: '/images/products/comforter-1.jpg',
        alt: 'Winter Silk Comforter',
        title: 'Winter Silk Comforter',
        description: 'Extra warm silk comforter for winter',
        href: 'winter-silk-comforter',
        categories: ['winter'],
      },
      {
        id: 4,
        image: '/images/products/blanket-1.jpg',
        alt: 'Summer Weight Silk Blanket',
        title: 'Summer Weight Silk Blanket',
        description: 'Lightweight silk blanket for summer nights',
        href: 'summer-weight-silk-blanket',
        categories: ['summer'],
      },
      {
        id: 5,
        image: '/images/products/kids-1.jpg',
        alt: 'Kids Silk Bedding Set',
        title: 'Kids Silk Bedding Set',
        description: 'Colorful silk bedding set for children',
        href: 'kids-silk-bedding-set',
        categories: ['children'],
      },
      {
        id: 6,
        image: '/images/products/organic-1.jpg',
        alt: 'Organic Silk Sheet Set',
        title: 'Organic Silk Sheet Set',
        description: 'GOTS certified organic silk sheets',
        href: 'organic-silk-sheet-set',
        categories: ['hotel'],
      },
      {
        id: 7,
        image: '/images/products/hotel-1.jpg',
        alt: 'Hotel Collection Duvet',
        title: 'Hotel Collection Duvet',
        description: 'Premium hotel quality silk duvet',
        href: 'hotel-collection-duvet',
        categories: ['hotel'],
      },
      {
        id: 8,
        image: '/images/products/throw-1.jpg',
        alt: 'Summer Silk Throw',
        title: 'Summer Silk Throw',
        description: 'Light silk throw for summer evenings',
        href: 'summer-silk-throw',
        categories: ['summer'],
      }
    ]